{% set name = "irida_uploader_cl" %}
{% set version = "0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
    url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
    sha256: "de3c5f8a85ec6f4962c1e3da89c06116f5f3ed806333c3cc5cfd413ec24e42d4"

build:
  number: 0
  entry_points:
    - irida_uploader_cl=irida_uploader_cl.irida_uploader_cl:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

channels:
  - defaults
  - conda-forge

requirements:
  host:
    - python==3.6
  run:
    - python==3.6
    - autopep8
    - pycodestyle
    - requests
    - appdirs
    - cerberus
    - argparse
    - selenium
    - rauth
    - mkdocs
    - pytest

about:
  home: "https://github.com/duanjunhyq/irida_uploader_cl"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "irida uploader: a tools used to upload NGS sequences to irida system"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - duanjunhyq
